mixed-port: 51837
allow-lan: false
mode: Rule
log-level: warn
external-controller: 0.0.0.0:9091
secret: "wisfern"

proxy-providers:
  BA:
    type: http
    path: ./profiles/proxies/BA.yaml
    url: "https://s.trojanflare.com/clashx/51e3a8cc-0727-4aac-af86-d3040b68ce17"
    interval: 3600
    filter: "HongKong|Japan"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800
  SS:
    type: http
    path: ./profiles/proxies/SS.yaml
    url: "https://s.trojanflare.com/clashx/51e3a8cc-0727-4aac-af86-d3040b68ce17"
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1801
  NOJOC:
    type: http
    url: "https://s.trojanflare.com/clashx/51e3a8cc-0727-4aac-af86-d3040b68ce17"
    path: ./profiles/proxies/NOJOC.yaml
    filter: Germany|Estonia|UnitedStates|Netherlands|UnitedKingdom|Japan
    interval: 86400
    health-check:
      enable: true
      interval: 1800
      url: http://www.gstatic.com/generate_204
  REPLIT:
    type: http
    path: ./profiles/proxies/replit.yaml
    url: "https://cdn.jsdelivr.net/gh/wisfern/dotfiles/vmess/replit.com.yml"
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1801

proxy-groups:
  - name: PROXY
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    lazy: true # 在策略组没有被使用时候，不进行延迟测试
    use:
      - REPLIT
      - SS
    #proxies:
    #  - DIRECT

  - name: BA_AUTO
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    lazy: true # 在策略组没有被使用时候，不进行延迟测试
    use:
      - REPLIT
      - BA
    #proxies:
    #  - DIRECT
    
  - name: NOJOC_PROXY
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    use:
      - NOJOC
      
  - name: Manual
    type: select
    proxies:  # 本文所定义的代理集
      - DIRECT
    use:  # 引用 proxy-providers所定义的远程代理集
      - REPLIT
      - SS
  #  proxies:
  #    - BA_AUTO
       
  # 白名单模式 PROXY，黑名单模式 DIRECT
  - name: Final
    type: select
    proxies:
      - PROXY
      - Manual
      - DIRECT
      
rule-providers:
  coin:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/wisfern/dotfiles/clash/ruleset/coin.yaml"
    path: ./ruleset/coin.yaml
    interval: 86400
  nojoc:
    type: http
    behavior: domain
    url: "url: "https://cdn.jsdelivr.net/gh/wisfern/dotfiles/clash/ruleset/nojoc.yaml"
    path: ./ruleset/nojoc.yaml
    interval: 86400
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

rules:
  - RULE-SET,nojoc,NOJOC_PROXY
  - RULE-SET,coin,BA_PROXY
  - DOMAIN-KEYWORD,binance,BA_PROXY
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,xray,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,leaf,DIRECT
  - PROCESS-NAME,v2ray.exe,DIRECT
  - PROCESS-NAME,xray.exe,DIRECT
  - PROCESS-NAME,naive.exe,DIRECT
  - PROCESS-NAME,trojan.exe,DIRECT
  - PROCESS-NAME,trojan-go.exe,DIRECT
  - PROCESS-NAME,ss-local.exe,DIRECT
  - PROCESS-NAME,privoxy.exe,DIRECT
  - PROCESS-NAME,leaf.exe,DIRECT
  - PROCESS-NAME,Surge,DIRECT
  - PROCESS-NAME,Surge 2,DIRECT
  - PROCESS-NAME,Surge 3,DIRECT
  - PROCESS-NAME,Surge 4,DIRECT
  - PROCESS-NAME,Surge%202,DIRECT
  - PROCESS-NAME,Surge%203,DIRECT
  - PROCESS-NAME,Surge%204,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - PROCESS-NAME,aria2c.exe,DIRECT
  - PROCESS-NAME,BitComet.exe,DIRECT
  - PROCESS-NAME,fdm.exe,DIRECT
  - PROCESS-NAME,NetTransport.exe,DIRECT
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - PROCESS-NAME,Thunder.exe,DIRECT
  - PROCESS-NAME,ThunderVIP.exe,DIRECT
  - PROCESS-NAME,transmission-daemon.exe,DIRECT
  - PROCESS-NAME,transmission-qt.exe,DIRECT
  - PROCESS-NAME,uTorrent.exe,DIRECT
  - PROCESS-NAME,WebTorrent.exe,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,DIRECT