test -s ~/.alias && . ~/.alias || true
test -s ~/.function && . ~/.function || true

export https_proxy=https://172.16.1.13:808
export http_proxy=http://172.16.1.13:808

export TERM=xterm-256color
export LESS=-R
